"""initial schema

Revision ID: b50f0629db44
Revises: 
Create Date: 2026-07-14 20:35:26.989053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50f0629db44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_level'), 'locations', ['level'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('OLX', 'ZAMEEN', 'GRAANA', name='sourcename'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_listing_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_price > 0', name='ck_listing_current_price_positive'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_listing_id', name='uq_listing_source_source_listing_id')
    )
    op.create_index(op.f('ix_listings_current_price'), 'listings', ['current_price'], unique=False)
    op.create_index(op.f('ix_listings_is_active'), 'listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_listings_location_id'), 'listings', ['location_id'], unique=False)
    op.create_index(op.f('ix_listings_source_id'), 'listings', ['source_id'], unique=False)
    op.create_index(op.f('ix_listings_source_listing_id'), 'listings', ['source_listing_id'], unique=False)
    op.create_table('location_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_aliases_alias'), 'location_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_location_aliases_location_id'), 'location_aliases', ['location_id'], unique=False)
    op.create_table('scrape_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED', name='scrapestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('listings_found', sa.Integer(), nullable=False),
    sa.Column('listings_new', sa.Integer(), nullable=False),
    sa.Column('resume_cursor', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_log_source_id'), 'scrape_log', ['source_id'], unique=False)
    op.create_index(op.f('ix_scrape_log_status'), 'scrape_log', ['status'], unique=False)
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('original_value', sa.Float(), nullable=False),
    sa.Column('original_unit', sa.Enum('MARLA', 'KANAL', 'SQFT', 'SQYD', name='sizeunit'), nullable=False),
    sa.Column('size_marla', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('original_value > 0', name='ck_dimension_original_value_positive'),
    sa.CheckConstraint('size_marla > 0', name='ck_dimension_size_marla_positive'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensions_listing_id'), 'dimensions', ['listing_id'], unique=True)
    op.create_index(op.f('ix_dimensions_size_marla'), 'dimensions', ['size_marla'], unique=False)
    op.create_table('duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_listing_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_listing_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('primary_listing_id != duplicate_listing_id', name='ck_duplicate_not_self'),
    sa.ForeignKeyConstraint(['duplicate_listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['primary_listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_listing_id', 'duplicate_listing_id', name='uq_duplicate_pair')
    )
    op.create_index(op.f('ix_duplicates_duplicate_listing_id'), 'duplicates', ['duplicate_listing_id'], unique=False)
    op.create_index(op.f('ix_duplicates_primary_listing_id'), 'duplicates', ['primary_listing_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('PKR', name='currency'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_price_history_price_positive'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    op.create_index(op.f('ix_price_history_observed_at'), 'price_history', ['observed_at'], unique=False)
    op.create_table('property_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.Enum('HOUSE', 'FLAT', 'PORTION', 'ROOM', 'UPPER_PORTION', 'LOWER_PORTION', 'FARM_HOUSE', 'PENTHOUSE', 'OTHER', name='propertytype'), nullable=False),
    sa.Column('portion_type', sa.Enum('FULL_HOUSE', 'UPPER_PORTION', 'LOWER_PORTION', 'ONE_ROOM', 'NOT_APPLICABLE', name='portiontype'), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=False),
    sa.Column('is_furnished', sa.Boolean(), nullable=False),
    sa.Column('is_corner', sa.Boolean(), nullable=False),
    sa.Column('is_park_facing', sa.Boolean(), nullable=False),
    sa.Column('has_servant_quarter', sa.Boolean(), nullable=False),
    sa.Column('has_independent_entrance', sa.Boolean(), nullable=False),
    sa.Column('is_newly_built', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bathrooms >= 0', name='ck_property_details_bathrooms_nonneg'),
    sa.CheckConstraint('bedrooms >= 0', name='ck_property_details_bedrooms_nonneg'),
    sa.CheckConstraint('parking_spaces >= 0', name='ck_property_details_parking_nonneg'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_details_listing_id'), 'property_details', ['listing_id'], unique=True)
    op.create_index(op.f('ix_property_details_property_type'), 'property_details', ['property_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_details_property_type'), table_name='property_details')
    op.drop_index(op.f('ix_property_details_listing_id'), table_name='property_details')
    op.drop_table('property_details')
    op.drop_index(op.f('ix_price_history_observed_at'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_duplicates_primary_listing_id'), table_name='duplicates')
    op.drop_index(op.f('ix_duplicates_duplicate_listing_id'), table_name='duplicates')
    op.drop_table('duplicates')
    op.drop_index(op.f('ix_dimensions_size_marla'), table_name='dimensions')
    op.drop_index(op.f('ix_dimensions_listing_id'), table_name='dimensions')
    op.drop_table('dimensions')
    op.drop_index(op.f('ix_scrape_log_status'), table_name='scrape_log')
    op.drop_index(op.f('ix_scrape_log_source_id'), table_name='scrape_log')
    op.drop_table('scrape_log')
    op.drop_index(op.f('ix_location_aliases_location_id'), table_name='location_aliases')
    op.drop_index(op.f('ix_location_aliases_alias'), table_name='location_aliases')
    op.drop_table('location_aliases')
    op.drop_index(op.f('ix_listings_source_listing_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_location_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_active'), table_name='listings')
    op.drop_index(op.f('ix_listings_current_price'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('sources')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_level'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
